import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import Providers from "@/app/providers/Providers";
import { cn } from "@/lib/utils"

import { Toaster } from "@/components/ui/toaster";
import config from "@/utils/config";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
console.log("==========================")
console.log("==========================")
console.log("==========================")
console.log("==========================")
console.log("==========================")
console.log("==========================")
console.log(config)


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <Providers>
          <Toaster />
          <div className={fontSans.className}>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
